### ISSUE TITLE
Tabort person (Händelse)

### ISSUE THREAD

**Issue by mahlbom** [LeafCoders/cordate#36]
Jag skulle önska att det gick att plocka bort en person från en händelse eftersom man kan göra fel när man lägger till personer.

Även så händer det att man byter tillfälle med varandra.

**Comment by OckePocke** [comment]
Jag har testat med Safari och Firefox och där kan man avmarkera en person. I listan med personer, som visas när du trycker på Tilldela, ska det gå att avmarkera en person genom att klicka på den. Händer det ingen när du klickar på personen?

**Comment by mahlbom** [comment]
Det fungerar, men det var inte hel uppenbart :)
Blir det för "kladdigt" att ha en kryssruta efter personen i händelsevyn?
