### ISSUE TITLE
Ska vi behålla sökfältet?

### ISSUE THREAD

**Issue by larsabrasha** [LeafCoders/cordate#6]
La till den för att testa, men tycker inte den behövs. Less is more.

**Comment by mahlbom** [comment]
Skulle det gå att använda detta som filter? Dvs. "Jag vill bara se Gudstjänster".

**Comment by OckePocke** [comment]
Jag har redan lagt till ett filter för resurstyper i terminsvyn för händelser. Den kommer med i en nyare version av Cordate.
